### ISSUE TITLE
Could not load the bindings

### ISSUE THREAD

**Issue by zeropaper** [lloyd/node-toobusy#10]
I just discovered the project and wanted to give it a try, installed using `npm install toobusy`, I followed the express example but when starting the application, the following error is thrown:

```
Error: Could not load the bindings file. Tried:
 → /home/robert/sites/requireexpress/node_modules/toobusy/build/toobusy.node
 → /home/robert/sites/requireexpress/node_modules/toobusy/build/Debug/toobusy.node
 → /home/robert/sites/requireexpress/node_modules/toobusy/build/Release/toobusy.node
 → /home/robert/sites/requireexpress/node_modules/toobusy/out/Debug/toobusy.node
 → /home/robert/sites/requireexpress/node_modules/toobusy/Debug/toobusy.node
 → /home/robert/sites/requireexpress/node_modules/toobusy/out/Release/toobusy.node
 → /home/robert/sites/requireexpress/node_modules/toobusy/Release/toobusy.node
 → /home/robert/sites/requireexpress/node_modules/toobusy/build/default/toobusy.node
 → /home/robert/sites/requireexpress/node_modules/toobusy/compiled/0.6.4/linux/x64/toobusy.node
    at bindings (/home/robert/sites/requireexpress/node_modules/toobusy/node_modules/bindings/bindings.js:84:13)
    at Object.<anonymous> (/home/robert/sites/requireexpress/node_modules/toobusy/index.js:1:96)
    at Module._compile (module.js:432:26)
    at Object..js (module.js:450:10)
    at Module.load (module.js:351:31)
    at Function._load (module.js:310:12)
    at Module.require (module.js:357:17)
    at require (module.js:368:17)
    at Object.<anonymous> (/home/robert/sites/requireexpress/app.js:2:15)
    at Module._compile (module.js:432:26)
```

Honestly, I'm clueless here and it doesn't seems to be related to my code (still.. I might be wrong on that ;) )... some advises would be welcome. Thanks!

**Comment by lloyd** [comment]
hmm.  is there an earlier error during npm install?  when you look in toobusy/build can you see built binaries?

do you have `g++` available on your system?  are you using node.js < 0.8.0?

**Comment by jsfunfun** [comment]
Similar issue for me... Is 'express' required for toobusy? While the example shows using express, the actual deps appear to be the 'fs' and'path' modules. In my case the bindings.js load fails because i don't have libuv on my system ... (and errrgggee don't intend to start using libuv in my prod system either - so unfortunately will have to roll my own notion of too busy).. and BTW when i npm install toobusy the toobusy.cc does correctly compile, so i think @zeropaper might have a similar aka no libuv issue... Cheers and nice work at ya @lloyd

**Comment by lloyd** [comment]
how about answers to those questions above?  I'd love to get to the bottom of this.  How about full npm install output?

**Comment by zeropaper** [comment]
Sorry for the late answer.. node is a bit old.. 0.6.4, gcc version is 4.6.1 (Ubuntu/Linaro 4.6.1-9ubuntu3) and it is a runtime error. Hope it helps.

**Comment by lloyd** [comment]
I'm confused.  package.json expresses a dependency on node.js `>=0.8.0`.

That said, there was a bug that manifested on windows, but could be the cause of this.  try version 0.2.2?

Re-open if you continue to have problems.
