### ISSUE TITLE
Stuck at node-gyp rebuild

### ISSUE THREAD

**Issue by didasy** [lloyd/node-toobusy#13]
OS@Ubuntu 12.10
Node@v0.8.18
toobusy@v0.2.2

I got this while installing from NPM

```
> toobusy@0.2.2 install /home/dida/nodejs/pics.kerok.in/node_modules/toobusy
> node-gyp rebuild

gyp http GET http://nodejs.org/dist/v0.8.18/node-v0.8.18.tar.gz
gyp http 200 http://nodejs.org/dist/v0.8.18/node-v0.8.18.tar.gz
```

and it stuck there forever.

**Comment by lloyd** [comment]
reproducible 100% of the time?

**Comment by didasy** [comment]
Yes, it still won't passed that on my machine. But it works flawlessly on my VPS ( also running 12.10 ).

**Comment by lloyd** [comment]
that's a big download.  could you be network constrained?

**Comment by didasy** [comment]
I don't really know, do you have any suggestion on how to test it?

**Comment by jrgm** [comment]
@JesusIslam - I'll suggest just doing the `npm install toobusy` and just let that run. There's no feedback while that process downloads and extracts the header files. On a "slow" connection with nothing previously cached it can take several minutes. Just see if it finishes "after a while".

**Comment by didasy** [comment]
@jrgm
@lloyd was right, it was my ISP. It somehow won't play nice with a big download over NPM.

Thank you, you can close this issue :)
