### ISSUE TITLE
Fails to install toobusy from npm on windows (Windows_NT 6.1.7601)

### ISSUE THREAD

**Issue by dkucinskas** [lloyd/node-toobusy#4]
Hi,

I'm not sure if this is right place for reporting this issue, but here it goes:

C:\pathtoapp>npm install toobusy
npm http GET https://registry.npmjs.org/toobusy
npm http 304 https://registry.npmjs.org/toobusy
npm http GET https://registry.npmjs.org/bindings/1.0.0
npm http 304 https://registry.npmjs.org/bindings/1.0.0

> toobusy@0.1.1 install C:\dev\git\blog-app\node_modules\toobusy
> node-gyp rebuild

C:\pathtoapp\node_modules\toobusy>node "C:\Program Files\nodejs\node_modu
les\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.Cpp.InvalidPlatform
.Targets(23,7): error MSB8007: The Platform for project 'toobusy.vcxproj' is in
valid.  Platform='x64'. You may be seeing this message because you are trying t
o build a project without a solution file, and have specified a non-default Pla
tform that doesn't exist for this project. [C:\pathtoapp\node_modules\to
obusy\build\toobusy.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:236:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:99:17)
gyp ERR! stack     at Process._handle.onexit (child_process.js:678:10)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\Program Files\nodejs\node_modules\npm\node_modu
les\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd C:\dev\git\blog-app\node_modules\toobusy
gyp ERR! node -v v0.8.15
gyp ERR! node-gyp -v v0.7.1
gyp ERR! not ok
npm ERR! toobusy@0.1.1 install: `node-gyp rebuild`
npm ERR! `cmd "/c" "node-gyp rebuild"` failed with 1
npm ERR!
npm ERR! Failed at the toobusy@0.1.1 install script.
npm ERR! This is most likely a problem with the toobusy package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls toobusy
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nod
ejs\node_modules\npm\bin\npm-cli.js" "install" "toobusy"
npm ERR! cwd C:\dev\git\blog-app
npm ERR! node -v v0.8.15
npm ERR! npm -v 1.1.66
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\pathtoapp\npm-debug.log
npm ERR! not ok code 0

**Comment by zhamid** [comment]
Same issue on Windows 7 and 8.  So it's not NT specific.

**Comment by dkucinskas** [comment]
Ok, my error here goes quote from node-gyp package documentation (gyp is used to build native node modules)

You will also need to install:
- On Windows:
  - Python (v2.7.3 recommended, v3.x.x is not supported)
  - Windows XP/Vista/7:
    - Microsoft Visual Studio C++ 2010 (Express version works well)
    - For 64-bit builds of node and native modules you will also need the Windows 7 64-bit SDK
    - If you get errors that the 64-bit compilers are not installed you may also need the compiler update for the /Windows SDK 7.1
  - Windows 8:
    - Microsoft Visual Studio C++ 2012 for Windows Desktop (Express version works well)
